#!/usr/bin/env bash
# shellcheck disable=SC2034,SC2089,SC2090
# =============================================================================
#     FileName : prompt
#       Author : marslo
#      Created : 2020-08-25 15:26:55
#   LastChange : 2026-05-16 15:28:40
# =============================================================================

# complex mode
# ╭╶ (USERNAME@HOSTNAME PATH) - (git-branch) - (venv) ->
# ╰╶ ᓆ  $
# simple mode
# ╭╶ (USERNAME) - (git-branch) - (venv) ->
# ╰╶ $

# /**************************************************************
#                             _
#  __ ___ _ __  _ __  ___ _ _| |_ ___
# / _/ _ \ '  \| '  \/ -_) ' \  _(_-<
# \__\___/_|_|_|_|_|_\___|_||_\__/__/
#
# **************************************************************/
# https://misc.flogisoft.com/bash/tip_colors_and_formatting
#    --------+--------    ----+------+------
#  | 0\;xxm | Normal |   | \e | \033 | \x1B |
#  | 1\;xxm | Bright |    ----+------+------
#   --------+--------              ---------------------------------
#   ----+---+---+----+---+----    |         UNICODE SYMBOL          |
#  | ⌌・| ⠋ | ⌜ | ╭╶ | ┌ | ┌─ |    ---------------------------------
#  | ⌎・| ⠦ | ⌞ | ╰╶ | └ | └─ |   | ✔ ✘ ⏵ ► ▶ ▷ ▸ ⌁ ↯ ✘ ö Ö ➜  ▶ ⨯ |
#   ----+---+---+----+---+----     ---------------------------------
#  ---+--------------++---------------------++----------------------+    +-----------------
# | # |  COLOR NAME  ||      FOREGRAND      ||      BACKGROUND      |    |   ATTRIBUTE     |
#  ---+--------------++---------------------++----------------------+    +---+-------------
# | 9 | Default      ||      \e[0;39m       ||       e[0;49m        |    | 0 | Normal      |
# | 0 | Black        || \e[0;30m |          || \e[0;40m |           |    | 1 | Bold        |
# | 1 | Red          || \e[0;31m |          || \e[0;41m |           |    | 2 | Faint       |
# | 2 | Green        || \e[0;32m |          || \e[0;42m |           |    | 3 | Italic      |
# | 3 | Yellow       || \e[0;33m |          || \e[0;43m |           |    | 4 | Underline   |
# | 4 | Blue         || \e[0;34m |          || \e[0;44m |           |    | 5 | Slow Blink  |
# | 5 | Magenta      || \e[0;35m |          || \e[0;45m |           |    | 6 | Rapid Blink |
# | 6 | Cyan         || \e[0;36m |          || \e[0;46m |           |    | 7 | reverse     |
# | 7 | Light Gray   || \e[0;37m |          || \e[0;47m |           |     ---+-------------
# | 0 | Dark Gray    || \e[1;30m | \e[0;90m || \e[1;40m | \e[0;100m |     ---------------------
# | 1 | Light Red    || \e[1;31m | \e[0;91m || \e[1;41m | \e[0;101m |    |       OTHERS        |
# | 2 | Light Green  || \e[1;32m | \e[0;92m || \e[1;42m | \e[0;102m |     -------------+-------
# | 3 | Light Yellow || \e[1;33m | \e[0;93m || \e[1;43m | \e[0;103m |    | color none  | \e[0m |
# | 4 | Light Blue   || \e[1;34m | \e[0;94m || \e[1;44m | \e[0;104m |    | color reset | \e[1m |
# | 5 | Light Magenta|| \e[1;35m | \e[0;95m || \e[1;45m | \e[0;105m |     -------------+-------
# | 6 | Light Cyan   || \e[1;36m | \e[0;96m || \e[1;46m | \e[0;106m |     ----------------+---------------------------------
# | 7 | White        ||      \e[0;97m       ||      \e[0;107m       |    | \[\e[xx;0m]\]  | system color                    |
#  ---+--------------++---------------------++----------------------     | \[\e[xx\;0m]\] | system color in ``              |
# |   |              ||  \e[38;5;{0..255}m# ||  \e[48;5;{0..255}m#  |    | \[\e[0;xxm]\]  | profile color (solarized)       |
#  ---+--------------++---------------------++----------------------     | \[\e[0\;xxm]\] | profile color (solarized) in `` |
#                                                                         ----------------+---------------------------------
#  ------------+-------------------------------------------------------   ----------------+-------------------------------
# |                   256 COLORS STANDARD FORMAT                       | |                   COMMENTS                     |
#  ------------+-------------------------------------------------------   ----------------+-------------------------------
# | attributes | 0 1 2 3 4 5 6 7                                       | | COL_NONE       | no color                      |
# | foregrand  | {0..255}                                              | | COL_RESET      | reset color                   |
# | background | {30..37} {90..97} 39                                  | | COL_DEFAULT    | default color                 |
#  ------------+-------------------------------------------------------  | COL_IF_DEFAULT | default color in if-statement |
# | usage : \e[${attributes};{background};5;${foreground}m <str> \e[0m |  ----------------+-------------------------------
#  ------------+-------------------------------------------------------

# /**************************************************************
#         _
#  __ ___| |___ _ _ ___
# / _/ _ \ / _ \ '_(_-<
# \__\___/_\___/_| /__/
#
# **************************************************************/
UMARK='\[\033(0\]l\[\033(B\]'
DMARK='\[\033(0\]m\[\033(B\]'
LMARK='\[\033(0\]q\[\033(B\]'

# L  - Bold/Bright/Light(1)
# D  - Dark/Dim(2)
# BD - Bold/Bright/Light(1) + Dark/Dim(2)

COL_GREEN='\[\033[0;32m\]'                        # COL_GREEN='\[\e[0;32m\]'
COL_BD_GREEN='\[\033[0;32;1;2m\]'                 # COL_BD_GREEN='\[\033[2;32m\]'
COL_BD_MAGENTA='\[\033[0;38;5;98;3m\]'            # 8 bit

COL_BLACK='\[\033[0;30m\]'
COL_D_BLACK='\[\033[0;30;2m\]'
COL_L_BLACK='\[\033[0;30;1m\]'
COL_BD_BLACK='\[\033[0;30;1;2m\]'
COL_RED='\[\033[0;31m\]'
COL_L_RED='\[\033[0;31;1m\]'
COL_D_RED='\[\033[0;31;2m\]'
COL_BD_RED='\[\033[0;31;1;2m\]'
COL_YELLOW='\[\033[0;33m\]'
COL_B_YELLOW='\[\033[0;33;2m\]'
COL_L_YELLOW='\[\033[0;33m;1\]'
COL_BD_YELLOW='\[\033[0;33;1;2m\]'
COL_IF_BD_YELLOW='\[\033[0\;33\;1\;2m\]'
COL_BLUE='\[\033[0;34m\]'
COL_BD_BLUE='\[\033[0;34;1;2m\]'

COL_IF_BLACK='\[\033[0\;30m\]'
COL_IF_D_BLACK='\[\033[0\;30\;2m\]'
COL_IF_L_BLACK='\[\033[0\;30\;1m\]'
COL_IF_BD_BLACK='\[\033[0\;30\;1;2m\]'
COL_IF_RED='\[\033[0\;31m\]'
COL_IF_D_RED='\[\033[0\;31\;1m\]'
COL_IF_BD_RED='\[\033[0\;31\;1\;2m\]'
COL_IF_GREEN='\[\033[0\;32m\]'
COL_IF_BD_GREEN='\[\033[0\;32\;1\;2m\]'
COL_IF_YELLOW='\[\033[0\;33m\]'
COL_IF_BLUE='\[\033[0\;34m\]'
COL_IF_BD_BLUE='\[\033[0\;34\;1\;2m\]'

# 38;5; for the foreground and 48;5; for the background : https://unix.stackexchange.com/a/124409/29178
function RGBcolor { echo "16 + $1 * 36 + $2 * 6 + $3" | bc; }

# https://marslo.github.io/ibook/screenshot/colors/ansi/color-formatting.png
fgc=$(RGBcolor 5 6 8)                             # 240;  fgc=$(RGBcolor 5 6 5)  # 237
# COL_DEFAULT=$"\e[38;5;${fgc}m"                  # COL_DEFAULT="\[$(tput -T $TERM setaf 237)\]" | COL_DEFAULT="\[\033[1;38;5;${fgc}m\]" | "${COL_BD_GREEN}"
COL_DEFAULT="\[\033[0;38;5;${fgc}m\]"             # "\[$(tput setaf ${fgc})\]"; $"\e[38;5;${fgc}m";
COL_IF_DEFAULT="\[\033[0\;38\;5\;${fgc}m\]"       # COL_IF_DEFAULT="\[\033[1\;38\;5\;${fgc}m\]"  | COL_IF_DEFAULT="${COL_IF_BD_GREEN}"
COL_RESET='\[\033[1m\]'                           # COL_RESET="\[$(tput sgr0)\]" | COL_RESET='\[\033[1m\]'
COL_NONE='\[\033[0m\]'                            # COL_NONE='\[\033[38;5;3m\]'

# /**************************************************************
#  ___  ___ _
# | _ \/ __/ |
# |  _/\__ \ |
# |_|  |___/_|
#
# PROMPT_START="\\n${COL_DEFAULT}╭╶ (\\u@\\h ${COL_RED}\\w${COL_DEFAULT}) "
# PROMPT_NEXT="\$(__git_ps1 \"- (${COL_BD_GREEN}%s${COL_NONE}${COL_DEFAULT}) \")"
# PROMPT_NEXT+="\$(__venv_info \"- (${COL_BD_MAGENTA}%s${COL_NONE}${COL_DEFAULT}) \")"
# PROMPT_NEXT+="${COL_DEFAULT}\`if [ \$? = 0 ]; then echo ${COL_IF_DEFAULT}\-\>; else echo ${COL_IF_RED}\↯; fi\`"
# PROMPT_END="\\n${COL_DEFAULT}\$ ${COL_NONE}"
# **************************************************************/
export PROMPT_MODE="${PROMPT_MODE:-complex}"
if [[ "${PROMPT_MODE}" == "simple" ]]; then
  export INPUTRC="${iRCHOME:-${HOME}/.marslo}/inputrc.d/.simplerc"
else
  export INPUTRC="${iRCHOME:-${HOME}/.marslo}/inputrc.d/.complexrc"
fi

# simple / complex: bind -f only these fragments (not ~/.inputrc — avoids resetting \C-r / fzf).
function pstoggle() {
  local _INPUTRC_COMPLEX="${iRCHOME:-${HOME}/.marslo}/inputrc.d/.complex"
  local _INPUTRC_SIMPLE="${iRCHOME:-${HOME}/.marslo}/inputrc.d/.simple"

  if [[ "${PROMPT_MODE}" == "complex" ]]; then
    export PROMPT_MODE="simple"
    export PS2="${COL_DEFAULT}   > ${COL_NONE}"
    [[ -r "${_INPUTRC_SIMPLE}" ]] && bind -f "${_INPUTRC_SIMPLE}"
  else
    export PROMPT_MODE="complex"
    export PS2='\[\e[G\e[K\]       '
    [[ -r "${_INPUTRC_COMPLEX}" ]] && bind -f "${_INPUTRC_COMPLEX}"
  fi
}

function __venv_info() {
  local exit_code=$?
  local format=' [%s]'
  local venv=''
  [[ $# -eq 1 ]] && format="$1"
  [[ -n "${VIRTUAL_ENV:-}" ]] && venv="${VIRTUAL_ENV##*/}"
  if [[ -n "${venv}" ]]; then
    # shellcheck disable=SC2059
    printf -- "${format}" "${venv}"
  fi
  return ${exit_code}
}

_build_prompt() {
  local status=$?

  local PROMPT_START=''
  local PROMPT_NEXT=''
  local PROMPT_END=''

  local VENV_RAW=''
  local PS1_VENV=''
  local GIT_RAW=''
  local PS1_GIT=''
  local PS1_STATUS=''

  # one-arg __git_ps1: pcmode=no → gitstring is printf'd to stdout (see git-prompt.sh).
  # add 127.0.0.1 localhost <HOSTNAME> and ::1 localhost <HOSTNAME> to /etc/hosts for better performance (avoid getent hosts <HOSTNAME>).
  GIT_RAW="$(__git_ps1 '%s' 2>/dev/null || true)"
  [[ -n "${GIT_RAW}"       ]] && PS1_GIT=" - (${COL_BD_GREEN}${GIT_RAW}${COL_NONE}${COL_DEFAULT})"
  [[ -n "${VIRTUAL_ENV:-}" ]] && VENV_RAW="${VIRTUAL_ENV##*/}"
  [[ -n "${VENV_RAW}"      ]] && PS1_VENV=" - (${COL_BD_MAGENTA}${VENV_RAW}${COL_NONE}${COL_DEFAULT})"
  [[ ${status} -eq 0       ]] && PS1_STATUS="${COL_DEFAULT} ->${COL_DEFAULT}" || PS1_STATUS="${COL_RED} ↯${COL_DEFAULT}"

  if [[ "${PROMPT_MODE}" = 'simple' ]]; then
    PROMPT_START="\n${COL_DEFAULT}╭╶ (\u${COL_DEFAULT} ${COL_RED}\W${COL_DEFAULT})"
    PROMPT_NEXT="${PS1_GIT}${PS1_VENV}${PS1_STATUS}"
    PROMPT_END="\n${COL_DEFAULT}╰╶ \$ ${COL_NONE}"
    PS1="${PROMPT_START}${PROMPT_NEXT}${PROMPT_END}"
    export PS2="${COL_DEFAULT}   > ${COL_NONE}"
  else
    # $COLUMNS requires: shopt -s checkwinsize
    local cols="${COLUMNS:-$(tput cols 2>/dev/null || printf '%s' 80)}"
    local HOST_RAW="${HOSTNAME%%.*}"
    local length=$(( 2 + 1 + 1 + ${#USER} + 1 + ${#HOST_RAW} + 1   ))
    [[ -n "${GIT_RAW}"  ]] && length=$(( length + 5 + ${#GIT_RAW}  ))
    [[ -n "${VENV_RAW}" ]] && length=$(( length + 5 + ${#VENV_RAW} ))
    length=$(( length + 3 + 2 ))

    local maxlength=$(( cols - length ))
    local p="${PWD/#$HOME/\~}"
    local smartPath="${p}"
    if (( ${#p} > maxlength )) && (( maxlength > 10 )); then
      smartPath="...${p: -$((maxlength - 3))}"
    fi

    PROMPT_START="\n${COL_DEFAULT}╭╶ (\u@${HOST_RAW} ${COL_RED}${smartPath}${COL_DEFAULT})"
    PROMPT_NEXT="${PS1_GIT}${PS1_VENV}${PS1_STATUS}"
    PROMPT_END="\n${COL_DEFAULT}\$ ${COL_NONE}"
    PS1="${PROMPT_START}${PROMPT_NEXT}${PROMPT_END}"
    export PS2='\[\e[G\e[K\]       '
  fi
}

# PS1
PROMPT_COMMAND=_build_prompt

# /**************************************************************
#  ___  ___ _ _
# | _ \/ __| | |
# |  _/\__ \_  _|
# |_|  |___/ |_|
#
# **************************************************************/
# set -x: wall-clock with milliseconds (EPOCHREALTIME: bash 5.1+; else python3)
function _ps4_ts() {
  local frac hms
  if [[ -n "${EPOCHREALTIME:-}" ]]; then
    printf -v hms '%(%Y-%m-%d %H:%M:%S)T' -1
    frac=${EPOCHREALTIME#*.}
    frac="${frac}000"
    printf '%s.%s' "${hms}" "${frac:0:3}"
  elif command -v python3 &>/dev/null; then
    python3 -c 'import datetime; print(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")[:-3])'
  else
    printf '%(%Y-%m-%d %H:%M:%S)T' -1
  fi
}

############ +[PID] (file:line): function(): ############
PS4='+\033[33;2m[${BASHPID:-$$}]\033[0m \033[37;2;3m(${BASH_SOURCE:+${BASH_SOURCE##*/}}\033[0m:\033[36;2;3m$(printf "%3d" ${LINENO})\033[0m\033[37;2;3m):\033[0m\033[35;2;3m${FUNCNAME[0]:+ ${FUNCNAME[0]}():}\033[0m '
# remove printf for better performance
# PS4='+\033[33;2m[${BASHPID:-$$}]\033[0m \033[37;2;3m(${BASH_SOURCE##*/}\033[0m:\033[36;2;3m${LINENO}\033[0m\033[37;2;3m):\033[0m\033[35;2;3m${FUNCNAME[0]:+ ${FUNCNAME[0]}():}\033[0m '
############ +(timestamp) [PID] (file:line): function(): (requires bash 5.1+) ############
# PS4='+\[\033[3;90m\]($(_ps4_ts))\[\033[0m\] \033[33;2m[${BASHPID:-$$}]\033[0m \033[37;2;3m(${BASH_SOURCE:+${BASH_SOURCE##*/}}\033[0m:\033[36;2;3m${LINENO}\033[0m\033[37;2;3m):\033[0m\033[35;2;3m${FUNCNAME[0]:+ ${FUNCNAME[0]}():}\033[0m '

if isWSL || isOSX; then
  export PS2 PS4
else
  [[ -z "${DISPLAY:-}" ]] && export PS2 PS4
fi

unset fgc UMARK DMARK LMARK

# vim:tabstop=2:softtabstop=2:shiftwidth=2:expandtab:filetype=sh:foldmethod=marker:foldmarker=#\ **************************************************************/,#\ /**************************************************************:
