#!/usr/bin/env bash
# shellcheck disable=SC1072,SC2154
# =============================================================================
#   FileName: docker
#     Author: marslo
#    Created: 2017-10-30 19:07:45
# LastChange: 2026-09-10 23:15:35
# =============================================================================

alias d='docker'
alias dkill='docker kill $(docker ps -a -q)'
alias dcleanc='docker rm $(docker ps -a -q)'
alias dcleani='docker rmi $(docker images -q -f dangling=true)'
alias dcleanall='dockercleanc || true && dockercleani'
alias dcleanfull='docker system prune -a -f'
alias dclraf='docker system prune -a -f'

alias dls='docker ps -l -q'
alias dps='docker ps -l -a'
alias dpa='docker ps -a'
alias dex='docker exec -i -t'
alias di='docker images'

alias drm='docker rm'
alias drmi='docker rmi'

alias drun='docker run -it -rm'
alias dexe='docker exec -i -t'
alias drit='docker run -i -t -P'
alias drdp='docker run -d -P'
alias drp='dockcer run --privileged -i -t'
alias droot='dockcer run --privileged -i -t -u 0'
alias drps='dockcer run --privileged -v /var/run/docker.sock:/var/run/docker.sock -i -t'
alias dip="docker inspect --format '{{ .NetworkSettings.IPAddress }}'"

# alias dv='docker volume'
alias dvi='docker volume inspect'


# bash completion for docker
if type -t __start_docker >/dev/null; then
  while read -r _i; do complete -F __start_docker "${_i}"; done < <(echo 'd')
  while read -r _i; do complete -F __start_docker "${_i}"; done < <(sed '/^alias /!d;s/^alias //;s/=.*$//' "${iRCHOME}/alias.d/docker")
elif type -t _docker >/dev/null; then
  # complete -F _complete_alias "${_i}"
  while read -r _i; do complete -F _docker "${_i}"; done < <(echo 'd')
  while read -r _i; do complete -F _docker "${_i}"; done < <(sed '/^alias /!d;s/^alias //;s/=.*$//' "${iRCHOME}/alias.d/docker")
fi

# vim:tabstop=2:softtabstop=2:shiftwidth=2:expandtab:filetype=sh
