#!/usr/bin/env bash
# shellcheck source=/dev/null disable=SC2015,SC2290,SC2139
# =============================================================================
#   FileName: utils
#     Author: marslo.jiao@gmail.com
#    Created: 2017-10-30 19:07:45
# LastChange: 2025-10-27 19:06:04
# =============================================================================

# using source instead of alias in ~/.marslo/.marslorc
# [[ -f "$HOME/.marslo/bin/help"    ]] && alias help='$HOME/.marslo/bin/help'
# [[ -f "$HOME/.marslo/bin/history" ]] && eval "$(cat "$HOME/.marslo/bin/history")"

if [[ 'Darwin' = $(uname --operating-system) ]]; then
  # requires gnu-which
  alias which='alias | which -a --tty-only --read-alias --show-dot --show-tilde'
  alias ping='/sbin/ping --apple-time -v'
  alias sping='/sbin/ping -c1 -t1 -W0'
  alias dropcache='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder'
else
  alias lvim="vim -c \"normal '0\""
  alias lgvim="gvim -c \"normal '0\""
  alias dropcache='sudo echo 3 > /proc/sys/vm/drop_caches'
  alias flushdns="sudo /etc/init.d/nscd restart"
  # shellcheck disable=SC2162
  alias howold="sudo tune2fs -l $(df -h / |(read; awk '{print $1; exit}')) | grep -i created"
fi

type -P trash >/dev/null      && alias rm='trash' || alias rm='rm -i'
test -x "$HOME/.npm/bin/tldr" && alias ntldr='$HOME/.npm/bin/tldr -t ocean'

# https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Aliases
# https://askubuntu.com/a/22043/92979
alias sudo='sudo '
alias cp='cp -i'
alias cpa='cp --parents'
alias mv='mv -i'

alias vv="$(type -P  vim) -Nu $HOME/.vimrc"
alias vi="$(type -P nvim) -Nu $HOME/.config/nvim/init.lua"
# alias vimdiff="$(type -P vim) -d"

# binding
alias bbon="bind 'set enable-bracketed-paste on'"
alias bboff="bind 'set enable-bracketed-paste off'"

# operation of files and directory
alias cx='chmod u+x'
alias cw='chmod u+w'
alias clr='clear'
# or printf '\e]1337;ClearScrollback\a'
alias totalclear='clear;printf %b "\033[3J"'
alias decolorize='sed -r "s/\x1B\[(([0-9]+)(;[0-9]+)*)?[mGKHfJ]//g"'
# alias decolorize='sed -r "s/\\x1B\\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g"'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias dc='cd'
alias sl='ls'
# alias cdl='cd $@ && ls -Altrh'

alias :q='exit'
alias :x='exit'

alias -- +='pushd .'
alias -- ++='pushd +1'
alias -- +++='pushd +2'
alias -- -='popd'
alias -- --='pushd -0'
alias -- ---='pushd -1'
alias dv='dirs -v'

# show colorful
## command grep -> /usr/local/opt/grep/libexec/gnubin/grep in mac
alias grep='command grep -i --color=always'
alias lgrep='command grep -i -n --color=always'
alias egrep='command egrep -i -n --color=always'
alias egp='command egrep -v "(#|^$)"'
alias h='history | grep -i --color=always'
alias his='history'
alias diff='diff --color=auto'
alias difft='difft --override="*.csv:LaTeX"'

if isOSX; then alias more='more -r'                ; fi
if isOSX; then alias man='man 2>/dev/null'         ; fi
if isOSX; then alias apropos='apropos 2>/dev/null' ; fi
alias makewhatis='/usr/libexec/makewhatis'

alias ld='\ls -alvd --color=always */'
alias ls='ls --color=always'
alias l='\ls -lvthr --color=always'
alias la='ls -Alvthr --color=always'
alias l.='ls -dv .* --color=always'
alias LS='find -mount -maxdepth 1 -printf "%.5m %10M %#9u:%-9g %#5U:%-5G %TF_%TR %CF_%CR %AF_%AR %#15s [%Y] %p\n" 2>/dev/null'
alias els='eza -al --group-directories-first --sort=modified --tree !(.git)'
alias ela='eza -al'

alias tmax='tmux at -t marslo'
alias ctmax='tmux new -s marslo -d && tmux at -t marslo'
alias ta='tmux at -t '
alias tls="tmux list-sessions -F '#{session_created} (created #{t/f/%y-%m-%d %H#:%M#:%S:window_activity}) - #{session_name}: #{session_windows} windows#{?session_grouped - (group ,}#{session_group}#{?session_grouped,),}#{?session_attached, [attached],}' | sort -Vr | sed 's/\S*\s//'"
alias tmuxls='tmux ls -F "#{session_created} #{session_name}: #{session_windows} windows (created #{t/f/%y-%m-%d %H#:%M#:%S:window_activity})#{?session_grouped, (group ,}#{session_group}#{?session_grouped,),}#{?session_attached, [attached],}" | sort -Vr | sed "s/\S*\s//"'

# alias polipo='polipo -c $HOME/.marslo/polipo/config daemonise=true >/dev/null 2>&1 &'
alias polipo='polipo -c $HOME/.marslo/polipo/config >/dev/null 2>&1 &'
alias myaws='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.marslo/Marslo/Tools/Softwares/sshkey/marslo-aws.pem ec2-user@ec2-54-193-78-97.us-west-1.compute.amazonaws.com'
alias startsslocal='sudo sslocal -c ~/mywork/job/code/marslo/backups/1.marslo_env/ubuntu/backups/ss/sslocal-config.json  -d start --log=/Users/marslo/.marslo/log/sslocal.log'
alias sshmarslo='ssh marslo@118.193.233.78'
alias nd='npm run deploy'
# alias rg='rg --hidden --follow --smart-case --vimgrep --ignore-file=$HOME/.rgignore --color=always'
alias rg='rg --hidden --follow --smart-case --ignore-file=$HOME/.rgignore --color=always'
alias as-tree='tree --fromfile'
# tree -F -> to show the `/` for directory
alias tree='tree -h --du'

alias ud='du -h --max-depth=1 --exclude="\./\.*"'
alias ud.='du -h --max-depth=1'
alias udf='du -skh'
alias uds='du --block-size=MiB --max-depth=1 --exclude="\./\.*" | sort -nr'
alias uds.='du --block-size=MiB --max-depth=1 | sort -nr'
alias df='df -kTh'
alias gerrit='ssh -p 29418 sample.gerrit.com gerrit'

alias chown='sudo chown'
alias chmod='sudo chmod'
alias service='sudo service'
alias systemctl='sudo systemctl'
# alias updatedb='sudo updatedb'
alias locate='sudo locate'
alias ports='sudo netstat -tunplea | grep'
alias reboot='sudo shutdown -r now'
alias lgout='read ans; kill -HUP $PPID'

alias showpath='echo -e ${PATH//:/\\n}'
alias showclasspath='echo -e ${CLASSPATH//:/\\n}'
alias showmanpath="manpath | tr ':' '\n'"
alias showfonts="fc-list | sed -re 's/^.+\/([^:]+):\s?([^,:]+),?:?.*$/\1 : \2/g' | column -t -s: -o: | sort -t: -k2"

alias cmount='mount | column -t'
alias dstat='dstat -cdgilmnprsy'
alias wget='wget --no-cookies --no-check-certificate --timeout=1 --tries=3 --retry-connrefused'
alias curl='command curl --insecure --globoff --netrc-file ~/.marslo/.netrc'
alias gcurl="command curl --insecure --globoff -H \"Accept: application/vnd.github+json\" -H \"User-Agent: curl\" -H \"Authorization: Bearer ${GITHUB_API_TOKEN}\""
alias myip='command curl --insecure --globoff -sS https://ipecho.net/plain'

alias lsock='sudo /usr/sbin/lsof -i -P'             # lsock:        Display open sockets
alias lsockU='sudo /usr/sbin/lsof -nP | grep UDP'   # lsockU:       Display only open UDP sockets
alias lsockT='sudo /usr/sbin/lsof -nP | grep TCP'   # lsockT:       Display only open TCP sockets
alias openPorts='sudo lsof -i | grep LISTEN'        # openPorts:    All listening connections
alias allowedports='sudo /sbin/iptables -L -n'

alias scp='scp -O -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null '
alias sshrsa="ssh -i ${MYWORKSPACE}/tools/remoteaccess/rsa/marslo@devops/marslo@devops"
alias sshpw='ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no'
alias rsync="rsync -avzrlpgoDP -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null '"
alias sudorsync="rsync -avzrlpgoDP -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ' --rsync-path='sudo rsync'"

alias imbusy='cat /dev/urandom | hexdump -C | grep "ca fe"'

alias weekno='date +"%V"'
alias daysleft='echo "There are $(($(date +%j -d"Dec 31, $(date +%Y)")-$(date +%j))) left in year $(date +%Y)."'
alias weather='curl wttr.in/sanjose?mMFn'
type -P npm-groovy-lint >/dev/null && alias npm-groovy-lint="$(type -P npm-groovy-lint) --failon warning --noserver"

# vim:tabstop=2:softtabstop=2:shiftwidth=2:expandtab:filetype=sh
