---

extends: default

rules:
  indentation:
    spaces: consistent
    indent-sequences: false

  line-length: disable

  braces:
    min-spaces-inside: 1
    max-spaces-inside: 1

  truthy:
    allowed-values: ['yes', 'no', 'true', 'false', 'on', 'off']
