[lint]
# explicitly ignore if the E/D series is enabled
ignore = [
  "E201",   # whitespace after '('
  "E202",   # whitespace before ')'
  "D210",   # no whitespaces surrounding docstring text
  "UP009",  # UTF-8 encoding declaration is unnecessary
  "EXE002", # file is executable but no shebang
]
