# -- reference --
# https://tldr.sh/tlrc/
# -- default config file path --
# $ tldr --config-path
# /Users/marslo/Library/Application Support/tlrc/config.toml
# -- default config --
# $ tldr --gen-config
# -- install --
# $ cat $0 | sudo tee $(tldr --config-path)

[cache]
dir = "~/Library/Caches/tlrc"
mirror = "https://github.com/tldr-pages/tldr/releases/latest/download"
auto_update = true
max_age = 336
languages = []

[output]
show_title = true
platform_title = false
show_hyphens = false
example_prefix = "- "
compact = false
raw_markdown = false

[indent]
title = 2
description = 2
bullet = 2
example = 4

[style.title]
color.hex = "#809f70"
background = "default"
bold = true
underline = true
italic = false
dim = false
strikethrough = false

[style.description]
color = "default"
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false

[style.bullet]
color.hex = "#979736"
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false

[style.example]
color.hex = "#739b6e"
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false

[style.url]
color.hex = "#ab5b54"
background = "default"
bold = false
underline = false
italic = true
dim = false
strikethrough = false

[style.inline_code]
color.hex = "#b2893a"
background = "default"
bold = false
underline = false
italic = true
dim = false
strikethrough = false

[style.placeholder]
color.hex = "#787464"
background = "default"
bold = false
underline = false
italic = true
dim = false
strikethrough = false
