#!/usr/bin/env bash
# shellcheck disable=SC2139,SC2034
# =============================================================================
#   FileName: devops
#     Author: marslo.jiao@gmail.com
#    Created: 2017-10-30 19:07:45
# LastChange: 2020-07-21 19:15:36
# =============================================================================

RTDOMAIN='pww.artifactory.cdi.philips.com'
M2_HOME="/opt/apache-maven-3.6.1"
if test -d "${M2_HOME}"; then
  MAVEN_OPTS="-Xms256m -Xmx512m"
  M2="${M2_HOME}/bin"
  PATH=$PATH:$M2
  export M2_HOME M2 MAVEN_OPTS PATH
fi

# alias pip="pip --trusted-hosts ${RTDOMAIN}"
# https://stackoverflow.com/a/18781512/2940319
# using git config --global pager.log 'diff-highlight | less -FRXK' instead of
# alias git='git --no-pager'

alias ipshow="ip addr show | sed -nE \"s/inet\s(.*)\/[0-9]+.*\s(\w+)/\2 \1/p\" | column -to ' => '"
alias en7dump='tcpdump -nni en7 -p'
alias startjack='jackd -d coreaudio &'
# alias mocp="mocp -v 50"
# alias npmuninstallall="npm uninstall `ls -1 node_modules | tr '/\n' ' '`; npm prune"

alias gradle="gradle --full-stacktrace"
alias gradler="gradle --full-stacktrace --refresh-dependencies"
alias gcl="gradle --full-stacktrace clean"

# groovy
alias groovydock="groovydoc -classpath /opt/groovy/lib"

# ldapsearch
# alias ldapsearch="ldapsearch -LLL -x -o ldif-wrap=no -H ldaps://msi-sldap.example.com:636 -b 'dc=example,dc=com' -D user -w password"

# vim:tabstop=2:softtabstop=2:shiftwidth=2:expandtab:filetype=sh
