#!/usr/bin/env bash
# shellcheck disable=SC2139,SC2034,SC2154
# =============================================================================
#   FileName : imarslo
#     Author : marslo.jiao@gmail.com
#    Created : 2017-10-30 19:07:45
# LastChange : 2024-07-26 19:30:51
# =============================================================================

MYWORKSPACE="$HOME/iMarslo"

alias irc="cd $HOME/.marslo"
alias desk="cd $HOME/Desktop"

alias cfg="cd ~/.config/"
alias vimd="cd ~/.marslo/vimrc.d"

alias mw="cd ${MYWORKSPACE}"
alias jo="cd ${MYWORKSPACE}/job"
alias jc="cd ${MYWORKSPACE}/job/code"
alias dos="cd ${MYWORKSPACE}/job/code/devops"
alias re="cd ${MYWORKSPACE}/job/code/re"
alias onf="cd ${MYWORKSPACE}/job/code/tool-config"

alias st="cd ${MYWORKSPACE}/study"
if [[ -d "${MYWORKSPACE}/study" ]]; then
  alias sc="cd ${MYWORKSPACE}/study/code"
  alias sts="cd ${MYWORKSPACE}/study/scripts"

  alias sg="cd ${MYWORKSPACE}/study/mystudy/groovy"
  alias sp="cd ${MYWORKSPACE}/study/mystudy/python"
  alias spc="cd ${MYWORKSPACE}/study/mystudy/python/leetcode"
  alias sk="cd ${MYWORKSPACE}/study/mystudy/kubernetes"
  alias cdjf="cd ${MYWORKSPACE}/study/mystudy/jenkinsfil"
  alias cdku="cd ${MYWORKSPACE}/study/mystudy/kubernetes"

  alias mco="cd ${MYWORKSPACE}/study/mycode"
  alias cdj="cd ${MYWORKSPACE}/study/mycode/devops"
  alias cdba="cd ${MYWORKSPACE}/study/code/backups"
  alias cdmac="cd ${MYWORKSPACE}/study/code/backups/1.marslo_env/mac"
  alias msp="cd ${MYWORKSPACE}/study/code/backups/1.marslo_env/belloMarslo/"
fi

alias to="cd ${MYWORKSPACE}/tools"
alias dl="cd ${MYWORKSPACE}/tools/download"
alias sf="cd ${MYWORKSPACE}/tools/software"
alias gi="cd ${MYWORKSPACE}/tools/git/marslo"
alias cddp="cd ${MYWORKSPACE}/tools/git/sandbox/deprecated"
alias ib="cd ${MYWORKSPACE}/tools/git/marslo/ibook/docs"
alias mi="cd ${MYWORKSPACE}/tools/git/marslo/myvim"
alias dm="cd ${MYWORKSPACE}/tools/git/marslo/dotfiles"
alias mt="cd ${MYWORKSPACE}/tools/git/marslo/mytools"
alias mb="cd ${MYWORKSPACE}/tools/git/marslo/mbook/docs >/dev/null"

if [[ '1' = "$(isWSL)" ]]; then
  alias dsk="cd $HOME/userprofile/Desktop"
  alias up="cd $HOME/userprofile"
  alias proj="cd ${MYWORKSPACE}/myprogramfiles"
  alias mw="cd '/home/marslo/userprofile/OneDrive - Marvell/iMarslo'"
  alias dos="cd '/home/marslo/userprofile/OneDrive - Marvell/iMarslo/job/devops'"
  alias clip='/mnt/c/Windows/System32/clip.exe'
  # alias pbcopy='/mnt/c/Windows/System32/clip.exe'
  alias pbcopy='wl-copy --trim-newline'
  alias bcomp='/mnt/c/Program\ Files/Beyond\ Compare\ 4/BComp.exe'
  # alias open='xdg-open'
  alias chrome='/mnt/c/Users/marslo/AppData/Local/Google/Chrome SxS/Application/chrome.exe'
  alias cygpath='/mnt/c/iMarslo/myprograms/Git/usr/bin/cygpath.exe'
  alias vscode='/mnt/c/Users/marslo/AppData/Local/Programs/Microsoft\ VS\ Code/Code.exe'
fi

# vim:tabstop=2:softtabstop=2:shiftwidth=2:expandtab:filetype=sh
