#!/usr/bin/env bash
# shellcheck disable=SC2139,SC2046,SC2142
# =============================================================================
#   FileName: kubernetes
#     Author: marslo.jiao@gmail.com
#    Created: 2017-10-30 19:07:45
# LastChange: 2024-05-21 18:12:00
# =============================================================================

alias kubectl='kubecolor'
alias k='kubecolor'
alias ka='kubeadm --namespace=kube-system'
alias kl='kubelet --namespace=kube-system'
alias kc='kubecolor --namespace=kube-system'

alias kcswatch='watch -n 1 kubectl --namespace=swcoe-system -o wide get all'
alias kubeproxy="kubectl proxy --address=\"0.0.0.0\" -p 8001 --accept-hosts='^*$' --accept-paths='^.*' --disable-filter=true"

alias  k3="kubecolor --kubeconfig ${MYWORKSPACE}/job/devops/env/linux/dc5-ssdfw3/.kube/config"
alias  k4="kubecolor --kubeconfig ${MYWORKSPACE}/job/devops/env/linux/dc5-ssdfw4/.kube/config"
alias  k8="kubecolor --kubeconfig ${MYWORKSPACE}/job/devops/env/linux/dc5-ssdfw8/.kube/config"
alias kt1="kubecolor --kubeconfig ${MYWORKSPACE}/job/devops/env/linux/dc5-ssdfwtst1/.kube/config"
alias kt2="kubecolor --kubeconfig ${MYWORKSPACE}/job/devops/env/linux/dc5-ssdfwtst2/.kube/config"
alias kt3="kubecolor --kubeconfig ${MYWORKSPACE}/job/devops/env/linux/dc5-ssdfwtst3/.kube/config"
alias kit="kubecolor --kubeconfig ${MYWORKSPACE}/job/devops/env/linux/it-k8s/.kube/config"
alias  kd="kubecolor --kubeconfig ${MYWORKSPACE}/job/devops/env/linux/dc5-ssdfw8/.kube/config --namespace devops-ci"
alias kre="kubecolor --kubeconfig ${MYWORKSPACE}/job/devops/env/linux/dockerreg1-sc/.kube/config"

# alias kcEvicted="kubecolor -n devops-ci get pods -o json | jq '.items[] | select(.status.reason!=null) | select(.status.reason | contains("Evicted")) | "kubecolor delete pods \(.metadata.name) -n \(.metadata.namespace)"' | xargs -n 1 bash -c"
alias kcEvicted="kubecolor get pods --all-namespaces --field-selector 'status.phase==Failed' -o json | kubecolor delete -f -"

alias kgc='kubecolor config get-contexts'
# get current context
alias krc='kubecolor config current-context'
# list all contexts
alias klc='kubecolor config get-contexts -o name | sed "s/^/  /;\|^  $(kubectl config current-context)$|s/ /*/"'
# change current context
alias kcc='kubecolor config use-context "$(kubectl config get-contexts -o name | sed "s/^/  /;\|^  $(kubecolor config current-context)$|s/ /*/" | fzf -e | sed "s/^..//")"'

# Get current namespace
alias krn='kubecolor config get-contexts --no-headers $(kubectl config current-context) | awk "{print \$5}" | sed "s/^$/default/"'
# List all namespaces
alias kln='kubecolor get -o name ns | sed "s|^.*/|  |;\|^  $(krn)$|s/ /*/"'
# Change current namespace
alias kcn='kubecolor config set-context --current --namespace "$(kln | fzf -e | sed "s/^..//")"'

# complete -F __start_kubectl k
# for _i in $(sed '/^alias /!d;s/^alias //;s/=.*$//' ${iRCHOME}/.alias/kubernetes); do
# done

# autocomplete for kubecolor
complete -o default -F __start_kubectl kubecolor

# for kubernetes
# complete -o nosort -o bashdefault -o default -F __start_kubectl $(alias | sed -rn 's/^alias ([^=]+)=.+kubec.+$/\1/p' | xargs)
complete -o nosort -o bashdefault -o default -F _complete_alias $(alias | sed -rn 's/^alias ([^=]+)=.+kubec.+$/\1/p' | xargs)

# while read -r _i; do
#   # complete -F _complete_alias "${_i}"
#   complete -o default -F __start_kubectl "${_i}"
# done < <(alias | sed -rn 's/^alias ([^=]+)=.+kubec.+$/\1/p')

# vim:tabstop=2:softtabstop=2:shiftwidth=2:expandtab:filetype=sh
