#!/usr/bin/env bash
# =============================================================================
#   FileName: mac
#     Author: marslo.jiao@gmail.com
#    Created: 2017-10-30 19:07:45
# LastChange: 2025-02-06 12:53:18
# =============================================================================

# shellcheck disable=SC2139
RTDOMAIN='pww.artifactory.cdi.philips.com'

alias sxcode92='sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer/'
alias sxcode833='sudo xcode-select -switch /Applications/Xcode8.3.3.app/Contents/Developer/'
alias cdwda='cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'

# Start/stop indexing on all volumes.
alias spotlight_off='sudo mdutil -a -i off'
alias spotlight_on='sudo mdutil -a -i on'

alias date="gdate"
alias alfredreindex='/Applications/Alfred 5.app/Contents/Frameworks/Alfred Framework.framework/Versions/A/Resources/reindex.sh'

# alias chrome="/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --disable-gpu"
alias chromec="'/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary' --disable-gpu"
alias chrome="'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' --disable-gpu"

alias dockerlogin="docker login --username marslo ${RTDOMAIN}"
# alias dockerstop="sudo killall Docker"
alias dockerstop="osascript -e 'tell app \"Docker\" to quit'"
alias dockerstart="open --hide --background -a Docker"
alias dockerrestart="sudo killall Docker && sleep 5 && open --hide --background -a Docker"

alias startproxy="bash -x '/Applications/Aventail Connect.app/Contents/MacOS/bin/startct.sh'"
alias restartsshd='sudo launchctl stop com.openssh.ssh-agent; sudo launchctl start com.openssh.ssh-agent;'
alias sshrestart='sudo launchctl stop com.openssh.ssh-agent; sudo launchctl start com.openssh.ssh-agent;'

alias bs='brew search'
alias bi='brew info'

# using clean [--lg | --ds |--dot] instead of
# alias removeDS='find . -name .DS_Store -print0 | xargs -0 git rm -f --ignore-unmatch'
# alias cleands="command fd --type f --hidden --follow --unrestricted --color=never --exclude .Trash --exclude 'OneDrive*' --glob '*\.DS_*' $HOME -x rm -rf"
# alias cleanlg="command fd --type f --hidden --follow --unrestricted --color=never --exclude .Trash --exclude 'OneDrive*' --glob '*\logback.log' $HOME -x rm -rf"

# vim:tabstop=2:softtabstop=2:shiftwidth=2:expandtab:filetype=sh
