#!/bin/bash
# shellcheck disable=SC1072,SC1127,SC2139,SC2142,SC2154
# =============================================================================
#   FileName: kuberntes
#     Author: marslo.jiao@gmail.com
#    Created: 2017-10-30 19:07:45
# LastChange: 2019-09-19 15:49:47
# =============================================================================

alias k='kubectl'
alias ka='kubeadm --namespace=kube-system'
alias kl='kubelet --namespace=kube-system'
alias kc='kubectl --namespace=kube-system'

alias kcswatch='watch -n 1 kubectl --namespace=swcoe-system -o wide get all'
alias kubeproxy="kubectl proxy --address=\"0.0.0.0\" -p 8001 --accept-hosts='^*$' --accept-paths='^.*' --disable-filter=true"

alias  k3="kubectl --kubeconfig ${MYWORKSPACE}/job/devops/env/linux/dc5-ssdfw3/.kube/config"
alias  k4="kubectl --kubeconfig ${MYWORKSPACE}/job/devops/env/linux/dc5-ssdfw4/.kube/config"
alias kt1="kubectl --kubeconfig ${MYWORKSPACE}/job/devops/env/linux/dc5-ssdfwtst1/.kube/config"
alias kt2="kubectl --kubeconfig ${MYWORKSPACE}/job/devops/env/linux/dc5-ssdfwtst2/.kube/config"
alias kt3="kubectl --kubeconfig ${MYWORKSPACE}/job/devops/env/linux/dc5-ssdfwtst3/.kube/config"
alias kit="kubectl --kubeconfig ${MYWORKSPACE}/job/devops/env/linux/it-k8s/.kube/config"

alias  kd='kubectl --kubeconfig ~/.kube/config --namespace devops-ci'
# alias kcEvicted="kubectl -n devops-ci get pods -o json | jq '.items[] | select(.status.reason!=null) | select(.status.reason | contains("Evicted")) | "kubectl delete pods \(.metadata.name) -n \(.metadata.namespace)"' | xargs -n 1 bash -c"
alias kcEvicted="kubectl get pods --all-namespaces --field-selector 'status.phase==Failed' -o json | kubectl delete -f -"

# Get current context
alias krc='kubectl config current-context'
# List all contexts
alias klc='kubectl config get-contexts -o name | sed "s/^/  /;\|^  $(kubectl config current-context)$|s/ /*/"'
# Change current context
alias kcc='kubectl config use-context "$(kubectl config get-contexts -o name | sed "s/^/  /;\|^  $(kubectl config current-context)$|s/ /*/" | fzf -e | sed "s/^..//")"'

# Get current namespace
alias krn='kubectl config get-contexts --no-headers $(kubectl config current-context) | awk "{print \$5}" | sed "s/^$/default/"'
# List all namespaces
alias kln='kubectl get -o name ns | sed "s|^.*/|  |;\|^  $(krn)$|s/ /*/"'
# Change current namespace
alias kcn='kubectl config set-context --current --namespace "$(kln | fzf -e | sed "s/^..//")"'

# complete -F __start_kubectl k
# for _i in $(sed '/^alias /!d;s/^alias //;s/=.*$//' ${iRCHOME}/.alias/kubernetes); do
# done

# for kubernetes
while read -r _i; do
  # complete -F _complete_alias "${_i}"
  complete -F __start_kubectl "${_i}"
done < <(sed '/^alias /!d;s/^alias //;s/=.*$//' "${iRCHOME}/.alias/kubernetes")
