#!/usr/bin/env bash
# =============================================================================
#   FileName: utils
#     Author: marslo.jiao@gmail.com
#    Created: 2017-10-30 19:07:45
# LastChange: 2023-11-14 15:58:14
# =============================================================================

# alias rm='rm -i'
# https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Aliases
# https://askubuntu.com/a/22043/92979
alias sudo='sudo '
alias rm='trash'
alias cp='cp -i'
alias cpa='cp --parents'
# alias cat='/usr/local/bin/ccat'
# alias mv='mv -i'

# Operation of files and directory
alias cx='chmod u+x'
alias cw='chmod u+w'
alias c='clear'
alias totalclear='clear;printf %b "\033[3J"'
alias decolorize='sed -r "s/\\x1B\\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g"'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias dc='cd'
alias sl='ls'
# alias cdl='cd $@ && ls -Altrh'

alias :q='exit'
alias :x='exit'

alias -- +='pushd .'
alias -- ++='pushd +1'
alias -- +++='pushd +2'
alias -- -='popd'
alias -- --='pushd -0'
alias -- ---='pushd -1'
alias dv='dirs -v'

# Show colorful
alias grep='grep -i --color=always'
alias lgrep='grep -i -n --color=always'
alias egrep='egrep -i -n --color=always'
alias egp='egrep -v "(#|^$)"'
alias h='history | grep -i --color=always'
alias his='history'
alias more='more -r'
alias diff='diff --color=auto'
alias fdiff="diff --old-group-format=$'\\e[0;31m%<\\e[0m' --new-group-format=$'\\e[0;31m%>\\e[0m' --unchanged-group-format=$'\\e[0;32m%=\\e[0m'"

alias ld='\ls -alvd --color=always */'
alias ls='ls --color=always'
alias l='\ls -lvthr --color=always'
alias la='ls -Alvthr --color=always'
alias l.='ls -dv .* --color=always'
alias LS='find -mount -maxdepth 1 -printf "%.5m %10M %#9u:%-9g %#5U:%-5G %TF_%TR %CF_%CR %AF_%AR %#15s [%Y] %p\n" 2>/dev/null'
alias o='open .'

alias lvim="vim -c \"normal '0\""
alias lgvim="gvim -c \"normal '0\""
# alias tig="tig 2> /dev/null"

alias c='clear'
alias ffx='firefox'
alias ud='du -h --max-depth=1 --exclude="\./\.*"'
alias ud.='du -h --max-depth=1'
alias udf='du -skh'
alias uds='du --block-size=MiB --max-depth=1 --exclude="\./\.*" | sort -nr'
alias uds.='du --block-size=MiB --max-depth=1 | sort -nr'
alias df='df -kTh'
alias which='alias | which -a --tty-only --read-alias --show-dot --show-tilde'
# alias which='alias | /usr/bin/which -a'
alias ping='/sbin/ping --apple-time -v'
alias sping='/sbin/ping -c1 -t1 -W0'
alias gerrit='ssh -p 29418 vgitcentral.mycompany.com gerrit'

alias chown='sudo chown'
alias chmod='sudo chmod'
alias service='sudo service'
alias systemctl='sudo systemctl'
# alias updatedb='sudo updatedb'
alias locate='sudo locate'
alias ports='sudo netstat -tunplea | grep'
alias reboot='sudo shutdown -r now'
# alias howold="sudo tune2fs -l $(df -h / |(read; awk '{print $1; exit}')) | grep -i created"
alias dropcache='sudo echo 3 > /proc/sys/vm/drop_caches'
alias lgout='read ans; kill -HUP $PPID'
alias showpath='echo -e ${PATH//:/\\n}'
alias cmount='mount | column -t'
alias dstat='dstat -cdgilmnprsy'
alias ta='tmux at -t '
alias tls='tmux ls'

alias wget='wget --no-cookies --no-check-certificate'
alias curl='/usr/local/opt/curl/bin/curl --netrc-file ~/.marslo/.netrc'
# alias curl='/usr/bin/curl --netrc-file ~/.marslo/.netrc'
alias clear-dns-cache='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder'
# alias myip='/usr/bin/curl ip.appspot.com'
alias myip='curl -sS https://ipecho.net/plain'

alias lsock='sudo /usr/sbin/lsof -i -P'             # lsock:        Display open sockets
alias lsockU='sudo /usr/sbin/lsof -nP | grep UDP'   # lsockU:       Display only open UDP sockets
alias lsockT='sudo /usr/sbin/lsof -nP | grep TCP'   # lsockT:       Display only open TCP sockets
alias openPorts='sudo lsof -i | grep LISTEN'        # openPorts:    All listening connections
alias allowedports='sudo /sbin/iptables -L -n'
alias flushdns="sudo /etc/init.d/nscd restart"

alias scp='scp -O -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null '
alias sshrsa="ssh -i ${MYWORKSPACE}/tools/remoteaccess/rsa/marslo@devops/marslo@devops"
alias rsync="rsync -avzrlpgoDP -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null '"
alias sudorsync="rsync -avzrlpgoDP -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ' --rsync-path='sudo rsync'"
# alias ssh="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "

alias imbusy='cat /dev/urandom | hexdump -C | grep "ca fe"'

alias weekno='date +"%V"'
alias daysleft='echo "There are $(($(date +%j -d"Dec 31, $(date +%Y)")-$(date +%j))) left in year $(date +%Y)."'
alias weather='curl wttr.in/sanjose?mMFn'

# bat
alias -- -h='-h 2>&1 | bat --language=help --style=plain'
alias -- --help='--help 2>&1 | bat --language=help --style=plain'

# vim: tabstop=2:softtabstop=2:shiftwidth=2:expandtab:filetype=sh
