#!/usr/bin/env bash
# shellcheck disable=SC2207
#=============================================================================
#     FileName : gh-new
#       Author : marslo
#      Created : 2026-02-27 23:04:41
#   LastChange : 2026-03-10 21:29:52
#=============================================================================

function _gh_new() {
  local cur opts
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"

  opts="-o --open -V --verbose -a --auto -D --dryrun -h --help"

  for (( i=1; i < COMP_CWORD; i++ )); do
    if [[ "${COMP_WORDS[i]}" == "--" ]]; then return 0; fi
  done

  if [[ ${cur} == -* ]] || [[ ${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
    return 0
  fi
}

complete -F _gh_new gh-new

# vim:tabstop=2:softtabstop=2:shiftwidth=2:expandtab:filetype=sh:
