#!/usr/bin/env bash
# shellcheck disable=SC2207
#=============================================================================
#     FileName : gh-ops
#       Author : marslo
#      Created : 2026-02-27 23:04:41
#   LastChange : 2026-03-10 21:29:19
#=============================================================================

function _gh_ops() {
  local cur prev opts
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  opts="-c --checkout
        -C --close
        -o --open
        -A --auto-open
        -s --squash
        -r --rebase
        -l --add-label
        -L --remove-label
        -M --comment
        -a --approve
        --request-changes
        -S --state
        -B --base
        -R --repo
        -V --verbose
        --dryrun
        -h --help"

  case "${prev}" in
    -S|--state )
        COMPREPLY=( $(compgen -W "open closed all merged" -- "${cur}") )
        return 0
        ;;
    -B|--base )
        local branches
        branches=$(git branch --format="%(refname:short)" 2>/dev/null)
        COMPREPLY=( $(compgen -W "${branches}" -- "${cur}") )
        return 0
        ;;
    -l|--add-label|-L|--remove-label|-R|--repo )
        COMPREPLY=()
        return 0
        ;;
  esac

  for (( i=1; i < COMP_CWORD; i++ )); do
    if [[ "${COMP_WORDS[i]}" == "--" ]]; then return 0; fi
  done

  if [[ ${cur} == -* ]] || [[ ${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
    return 0
  fi
}

complete -F _gh_ops gh-ops

# vim:tabstop=2:softtabstop=2:shiftwidth=2:expandtab:filetype=sh:
