#!/usr/bin/env bash
# shellcheck disable=SC2089,SC2090
# =============================================================================
#     FileName : fzf
#       Author : marslo
#      Created : 2020-08-25 15:26:55
#   LastChange : 2026-05-11 15:00:06
# =============================================================================

# fzf
FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS} "
FZF_DEFAULT_OPTS+="--height 35% --min-height 8+ "             # https://github.com/junegunn/fzf/issues/4226
FZF_DEFAULT_OPTS+="--layout=default --multi --cycle --ansi --gutter ' ' "
FZF_DEFAULT_OPTS+="--border=rounded "
FZF_DEFAULT_OPTS+="--marker='󱍢 ' --pointer='▌' "
FZF_DEFAULT_OPTS+="--prompt='󰩀 ' --info='inline: 󰨿 ' "
FZF_DEFAULT_OPTS+="--info-command='printf \"\x1b[33;1m%s\x1b[m ~ %s\" \"\$FZF_POS\" \"\$FZF_INFO\"' "
FZF_DEFAULT_OPTS+="--bind 'ctrl-s:select-all,ctrl-d:deselect-all,ctrl-t:toggle-all' "
FZF_DEFAULT_OPTS+="--bind 'ctrl-y:execute-silent(/bin/echo -n {+} | ${COPY})' "
FZF_DEFAULT_OPTS+="--color=gutter:0,bg+:-1,query:italic,spinner:#e6db74,prompt:italic:#404945,header:italic:#504945,info:#928374,pointer:#A66584,marker:#d79921,fg:#ebdbb2:dim,fg+:#A7A44E:regular,hl:#845069:italic,hl+:#A66584:bold:italic"

FZF_DEFAULT_COMMAND="fd --type f "
FZF_DEFAULT_COMMAND+="--strip-cwd-prefix "
FZF_DEFAULT_COMMAND+="--hidden "
FZF_DEFAULT_COMMAND+="--follow "
FZF_DEFAULT_COMMAND+="--exclude .git --exclude node_modules"

PROMPT_STR=$(printf "\e[38;5;240;1m╰╶ ᓆ $ \e[0m")

# ctrl-t for preview with bat
FZF_CTRL_T_OPTS="${FZF_CTRL_T_OPTS:+$FZF_CTRL_T_OPTS} "
FZF_CTRL_T_OPTS+="--height 80% "
FZF_CTRL_T_OPTS+="--layout=reverse "
FZF_CTRL_T_OPTS+="--prompt='${PROMPT_STR}' --info=hidden "
FZF_CTRL_T_OPTS+="--no-border --no-input-border --header-lines-border bottom "
FZF_CTRL_T_OPTS+="--preview '([[ -f {} ]] && (bat --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200' "
FZF_CTRL_T_OPTS+="--bind 'enter:become:command nvim {} >/dev/tty' "
FZF_CTRL_T_OPTS+="--bind 'ctrl-\:change-preview-window(down|hidden|)' "
FZF_CTRL_T_OPTS+="--bind 'ctrl-p:preview-up,ctrl-n:preview-down' "
FZF_CTRL_T_OPTS+="--bind 'ctrl-y:execute-silent(/bin/echo -n {+} | ${COPY})' "
FZF_CTRL_T_OPTS+="--header 'CTRL-N/CTRL-P to view contents, CTRL-/ to change previous window'"
# FZF_CTRL_T_OPTS+=" --bind 'ctrl-e:become:command cd {} >/dev/tty'"

# ctrl-r for filter history
FZF_CTRL_R_OPTS="${FZF_CTRL_R_OPTS:+$FZF_CTRL_R_OPTS} "
FZF_CTRL_R_OPTS+="--height '30%' "
FZF_CTRL_R_OPTS+="--layout=reverse "
FZF_CTRL_R_OPTS+="--prompt='${PROMPT_STR}' --info=hidden "
FZF_CTRL_R_OPTS+="--no-border --header-lines-border bottom --no-list-border "
FZF_CTRL_R_OPTS+="--preview 'echo {}' --preview-window down:5:hidden:wrap "
FZF_CTRL_R_OPTS+="--bind 'ctrl-\:toggle-preview' "
FZF_CTRL_R_OPTS+="--bind 'ctrl-y:execute-silent(echo {2..} | ${COPY})+abort' "
FZF_CTRL_R_OPTS+="--color header:italic "
FZF_CTRL_R_OPTS+="--header 'CTRL-Y to copy command into clipboard'"

export FZF_COMPLETION_TRIGGER=',,'
export FZF_COMPLETION_DIR_COMMANDS="cd pushd rmdir tree"
export FZF_COMPLETION_OPTS='--border --info=inline'
export FZF_COMPLETION_DIR_OPTS='--walker dir,follow'
export FZF_COMPLETION_PATH_OPTS='--walker file,dir,follow,hidden'
export FZF_ALT_C_OPTS="--height 60% --walker-skip .git,node_modules,target --preview 'tree -C {}'"       # print tree structure in the preview window
export FZF_COMPLETION_PATH_COMMANDS="basename bunzip2 bzip2 chmod chown curl cp dirname ls mv rm open tar unzip du sftp rsync"
export FZF_DEFAULT_OPTS FZF_DEFAULT_COMMAND FZF_CTRL_T_OPTS FZF_CTRL_R_OPTS

export FD_IGNORE_FILE="${HOME}/.fdignore"

# vim:tabstop=2:softtabstop=2:shiftwidth=2:expandtab:filetype=sh:
