#!/usr/bin/env bash

[ -z "$(git config remote.origin.url)" ] && exit 0

# only run on the first checkout after cloning
# if [[ "$3" = '1' ]]; then
if [[ "$1" = "0000000000000000000000000000000000000000" || "$3" = '1' ]]; then
  ~/.marslo/gitconfig.d/bin/set-git-user.sh
fi

# vim:tabstop=2:softtabstop=2:shiftwidth=2:expandtab:filetype=sh:
