#!/usr/bin/env bash

set -euo pipefail

### git-stats hook (begin) ###
# Copy last commit hash to clipboard on commit
commit_hash=$(git rev-parse HEAD)
repo_url=$(git config --get remote.origin.url)
commit_date=$(git log -1 --format=%cI)
commit_data="\"{ \"date\": \"${commit_date}\", \"url\": \"${repo_url}\", \"hash\": \"${commit_hash}\" }\""
git-stats --record "${commit_data}"
### git-stats hook (end) ###

# vim:tabstop=2:softtabstop=2:shiftwidth=2:expandtab:filetype=sh:
