#!/usr/bin/env bash

# if [ -f $(brew --prefix)/etc/bash_completion ]; then
  # source $(brew --prefix)/etc/bash_completion;
# fi

# [ -f /Users/marslo/.marslo/.marslorc ] && source /Users/marslo/.marslo/.marslorc

# https://brettterpstra.com/2014/07/12/making-cd-in-bash-a-little-better/
# export FIGNORE="Application Scripts:Applications (Parallels):ScrivWatcher:ScriptingAdditions"

# vim: tabstop=2:softtabstop=2:shiftwidth=2:expandtab:filetype=sh
